#include "gpu/HdrBridge.h"

#include "gpu/Shaders/HdrToSdr.cs.h"     // generated by dxc at build time
#include "gpu/Shaders/HdrCompose.cs.h"

using Microsoft::WRL::ComPtr;

namespace sidecar {
namespace {

constexpr uint32_t kDescriptorsPerSlot = 4;   // up to t0..t2 and u0
constexpr uint32_t kSlotToSdr = 0;
constexpr uint32_t kSlotCompose = 1;

struct Constants {
  uint32_t width;
  uint32_t height;
  float a;   // paper white, scRGB units
  float b;   // headroom (to-SDR) or max gain (compose)
  float c;   // headroom (compose); unused by to-SDR
  float d;   // split fraction (compose); unused by to-SDR
};

ComPtr<ID3D12PipelineState> MakePso(ID3D12Device* device, ID3D12RootSignature* rs,
                                    const void* bytecode, size_t length) {
  D3D12_COMPUTE_PIPELINE_STATE_DESC psd{};
  psd.pRootSignature = rs;
  psd.CS.pShaderBytecode = bytecode;
  psd.CS.BytecodeLength = length;
  ComPtr<ID3D12PipelineState> pso;
  if (FAILED(device->CreateComputePipelineState(&psd, IID_PPV_ARGS(&pso)))) return nullptr;
  return pso;
}

}  // namespace

std::unique_ptr<HdrBridge> HdrBridge::Create(ID3D12Device* device, uint32_t width,
                                             uint32_t height) {
  if (!device || width == 0 || height == 0) return nullptr;
  std::unique_ptr<HdrBridge> b(new HdrBridge());
  b->device_ = device;
  b->width_ = width;
  b->height_ = height;

  D3D12_DESCRIPTOR_RANGE ranges[2]{};
  ranges[0].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
  ranges[0].NumDescriptors = 3;
  ranges[0].BaseShaderRegister = 0;
  ranges[1].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_UAV;
  ranges[1].NumDescriptors = 1;
  ranges[1].BaseShaderRegister = 0;
  ranges[1].OffsetInDescriptorsFromTableStart = 3;

  D3D12_ROOT_PARAMETER params[2]{};
  params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
  params[0].DescriptorTable.NumDescriptorRanges = 2;
  params[0].DescriptorTable.pDescriptorRanges = ranges;
  params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
  params[1].Constants.Num32BitValues = sizeof(Constants) / 4;
  params[1].Constants.ShaderRegister = 0;

  D3D12_ROOT_SIGNATURE_DESC rsd{};
  rsd.NumParameters = 2;
  rsd.pParameters = params;

  ComPtr<ID3DBlob> blob, error;
  if (FAILED(D3D12SerializeRootSignature(&rsd, D3D_ROOT_SIGNATURE_VERSION_1, &blob, &error))) {
    return nullptr;
  }
  if (FAILED(device->CreateRootSignature(0, blob->GetBufferPointer(), blob->GetBufferSize(),
                                         IID_PPV_ARGS(&b->rootSignature_)))) {
    return nullptr;
  }
  b->toSdr_ = MakePso(device, b->rootSignature_.Get(), g_HdrToSdrCS, sizeof(g_HdrToSdrCS));
  b->compose_ = MakePso(device, b->rootSignature_.Get(), g_HdrComposeCS, sizeof(g_HdrComposeCS));
  if (!b->toSdr_ || !b->compose_) return nullptr;

  D3D12_DESCRIPTOR_HEAP_DESC hd{};
  hd.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
  hd.NumDescriptors = kDescriptorsPerSlot * 2;
  hd.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
  if (FAILED(device->CreateDescriptorHeap(&hd, IID_PPV_ARGS(&b->heap_)))) return nullptr;
  b->descriptorSize_ =
      device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
  return b;
}

namespace {

void Bind(ID3D12Device* device, D3D12_CPU_DESCRIPTOR_HANDLE& cpu, UINT step,
          ID3D12Resource* srv0, ID3D12Resource* srv1, ID3D12Resource* srv2,
          ID3D12Resource* uav) {
  D3D12_SHADER_RESOURCE_VIEW_DESC srv{};
  srv.ViewDimension = D3D12_SRV_DIMENSION_TEXTURE2D;
  srv.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
  srv.Texture2D.MipLevels = 1;
  ID3D12Resource* sources[3] = {srv0, srv1 ? srv1 : srv0, srv2 ? srv2 : srv0};
  for (ID3D12Resource* source : sources) {
    srv.Format = source->GetDesc().Format;
    device->CreateShaderResourceView(source, &srv, cpu);
    cpu.ptr += step;
  }
  D3D12_UNORDERED_ACCESS_VIEW_DESC uavd{};
  uavd.Format = uav->GetDesc().Format;
  uavd.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;
  device->CreateUnorderedAccessView(uav, nullptr, &uavd, cpu);
}

}  // namespace

void HdrBridge::RecordToSdr(ID3D12GraphicsCommandList* cl, ID3D12Resource* hdr,
                            ID3D12Resource* sdr, const Params& params) {
  if (!cl || !hdr || !sdr) return;
  auto cpu = heap_->GetCPUDescriptorHandleForHeapStart();
  cpu.ptr += static_cast<SIZE_T>(kSlotToSdr) * kDescriptorsPerSlot * descriptorSize_;
  Bind(device_.Get(), cpu, descriptorSize_, hdr, nullptr, nullptr, sdr);

  auto gpu = heap_->GetGPUDescriptorHandleForHeapStart();
  gpu.ptr += static_cast<UINT64>(kSlotToSdr) * kDescriptorsPerSlot * descriptorSize_;

  Constants c{width_, height_, params.paperWhiteNits / 80.0f, params.headroom, params.headroom,
              0.0f};
  ID3D12DescriptorHeap* heaps[] = {heap_.Get()};
  cl->SetDescriptorHeaps(1, heaps);
  cl->SetComputeRootSignature(rootSignature_.Get());
  cl->SetPipelineState(toSdr_.Get());
  cl->SetComputeRootDescriptorTable(0, gpu);
  cl->SetComputeRoot32BitConstants(1, sizeof(Constants) / 4, &c, 0);
  cl->Dispatch((width_ + 7) / 8, (height_ + 7) / 8, 1);
}

void HdrBridge::RecordCompose(ID3D12GraphicsCommandList* cl, ID3D12Resource* hdr,
                              ID3D12Resource* sdrShown, ID3D12Resource* sdrResult,
                              ID3D12Resource* dst, const Params& params) {
  if (!cl || !hdr || !sdrShown || !sdrResult || !dst) return;
  auto cpu = heap_->GetCPUDescriptorHandleForHeapStart();
  cpu.ptr += static_cast<SIZE_T>(kSlotCompose) * kDescriptorsPerSlot * descriptorSize_;
  Bind(device_.Get(), cpu, descriptorSize_, hdr, sdrShown, sdrResult, dst);

  auto gpu = heap_->GetGPUDescriptorHandleForHeapStart();
  gpu.ptr += static_cast<UINT64>(kSlotCompose) * kDescriptorsPerSlot * descriptorSize_;

  Constants c{width_, height_, params.paperWhiteNits / 80.0f, params.maxGain, params.headroom,
              params.split};
  ID3D12DescriptorHeap* heaps[] = {heap_.Get()};
  cl->SetDescriptorHeaps(1, heaps);
  cl->SetComputeRootSignature(rootSignature_.Get());
  cl->SetPipelineState(compose_.Get());
  cl->SetComputeRootDescriptorTable(0, gpu);
  cl->SetComputeRoot32BitConstants(1, sizeof(Constants) / 4, &c, 0);
  cl->Dispatch((width_ + 7) / 8, (height_ + 7) / 8, 1);
}

}  // namespace sidecar
