#include "gpu/NrColorBridge.h"

#include "gpu/Shaders/NrEncode.cs.h"    // generated by dxc at build time
#include "gpu/Shaders/NrResolve.cs.h"
#include "gpu/Shaders/NrCompose.cs.h"

using Microsoft::WRL::ComPtr;

namespace sidecar {
namespace {

constexpr uint32_t kDescriptorsPerSlot = 4;   // t0, t1, t2, u0

// Mirrors the cbuffer in all three shaders.
struct Constants {
  uint32_t width;
  uint32_t height;
  float paperWhite;
  float headroom;
  float strength;
  float colourPreserve;
  float highlightProtect;
  float split;
};

ComPtr<ID3D12PipelineState> MakePso(ID3D12Device* device, ID3D12RootSignature* rs,
                                    const void* bytecode, size_t length) {
  D3D12_COMPUTE_PIPELINE_STATE_DESC psd{};
  psd.pRootSignature = rs;
  psd.CS.pShaderBytecode = bytecode;
  psd.CS.BytecodeLength = length;
  ComPtr<ID3D12PipelineState> pso;
  if (FAILED(device->CreateComputePipelineState(&psd, IID_PPV_ARGS(&pso)))) return nullptr;
  return pso;
}

}  // namespace

std::unique_ptr<NrColorBridge> NrColorBridge::Create(ID3D12Device* device) {
  if (!device) return nullptr;
  std::unique_ptr<NrColorBridge> b(new NrColorBridge());
  b->device_ = device;

  D3D12_DESCRIPTOR_RANGE ranges[2]{};
  ranges[0].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
  ranges[0].NumDescriptors = 3;
  ranges[0].BaseShaderRegister = 0;
  ranges[1].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_UAV;
  ranges[1].NumDescriptors = 1;
  ranges[1].BaseShaderRegister = 0;
  ranges[1].OffsetInDescriptorsFromTableStart = 3;

  D3D12_ROOT_PARAMETER params[2]{};
  params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
  params[0].DescriptorTable.NumDescriptorRanges = 2;
  params[0].DescriptorTable.pDescriptorRanges = ranges;
  params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
  params[1].Constants.Num32BitValues = sizeof(Constants) / 4;
  params[1].Constants.ShaderRegister = 0;

  // One linear-clamp sampler, so sources of a different size than the
  // destination are resampled rather than read off the edge.
  D3D12_STATIC_SAMPLER_DESC sampler{};
  sampler.Filter = D3D12_FILTER_MIN_MAG_MIP_LINEAR;
  sampler.AddressU = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
  sampler.AddressV = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
  sampler.AddressW = D3D12_TEXTURE_ADDRESS_MODE_CLAMP;
  sampler.MaxLOD = D3D12_FLOAT32_MAX;
  sampler.ShaderRegister = 0;
  sampler.ShaderVisibility = D3D12_SHADER_VISIBILITY_ALL;

  D3D12_ROOT_SIGNATURE_DESC rsd{};
  rsd.NumParameters = 2;
  rsd.pParameters = params;
  rsd.NumStaticSamplers = 1;
  rsd.pStaticSamplers = &sampler;

  ComPtr<ID3DBlob> blob, error;
  if (FAILED(D3D12SerializeRootSignature(&rsd, D3D_ROOT_SIGNATURE_VERSION_1, &blob, &error))) {
    return nullptr;
  }
  if (FAILED(device->CreateRootSignature(0, blob->GetBufferPointer(), blob->GetBufferSize(),
                                         IID_PPV_ARGS(&b->rootSignature_)))) {
    return nullptr;
  }

  b->encode_ = MakePso(device, b->rootSignature_.Get(), g_NrEncodeCS, sizeof(g_NrEncodeCS));
  b->resolve_ = MakePso(device, b->rootSignature_.Get(), g_NrResolveCS, sizeof(g_NrResolveCS));
  b->compose_ = MakePso(device, b->rootSignature_.Get(), g_NrComposeCS, sizeof(g_NrComposeCS));
  if (!b->encode_ || !b->resolve_ || !b->compose_) return nullptr;

  D3D12_DESCRIPTOR_HEAP_DESC hd{};
  hd.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
  hd.NumDescriptors = kDescriptorsPerSlot * kSlots;
  hd.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
  if (FAILED(device->CreateDescriptorHeap(&hd, IID_PPV_ARGS(&b->heap_)))) return nullptr;
  b->descriptorSize_ =
      device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);
  return b;
}

void NrColorBridge::Record(ID3D12GraphicsCommandList* cl, ID3D12PipelineState* pso,
                           uint32_t slot, ID3D12Resource* srv0, ID3D12Resource* srv1,
                           ID3D12Resource* srv2, ID3D12Resource* uav, uint32_t dstWidth,
                           uint32_t dstHeight, const NrBridgeParams& params) {
  if (!cl || !srv0 || !uav || slot >= kSlots || dstWidth == 0 || dstHeight == 0) return;

  auto cpu = heap_->GetCPUDescriptorHandleForHeapStart();
  cpu.ptr += static_cast<SIZE_T>(slot) * kDescriptorsPerSlot * descriptorSize_;

  D3D12_SHADER_RESOURCE_VIEW_DESC srv{};
  srv.ViewDimension = D3D12_SRV_DIMENSION_TEXTURE2D;
  srv.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
  srv.Texture2D.MipLevels = 1;
  // Unused inputs bind the first, so the table never holds a stale view.
  ID3D12Resource* sources[3] = {srv0, srv1 ? srv1 : srv0, srv2 ? srv2 : srv0};
  for (ID3D12Resource* source : sources) {
    srv.Format = source->GetDesc().Format;
    device_->CreateShaderResourceView(source, &srv, cpu);
    cpu.ptr += descriptorSize_;
  }

  // The destination's own format: RGBA16F for an intermediate, BGRA8 when the
  // final compose writes the presentable target directly and the resolve pass
  // is skipped. The shader stores float4; the view converts.
  D3D12_UNORDERED_ACCESS_VIEW_DESC uavd{};
  uavd.Format = uav->GetDesc().Format;
  uavd.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;
  device_->CreateUnorderedAccessView(uav, nullptr, &uavd, cpu);

  auto gpu = heap_->GetGPUDescriptorHandleForHeapStart();
  gpu.ptr += static_cast<UINT64>(slot) * kDescriptorsPerSlot * descriptorSize_;

  Constants c{};
  c.width = dstWidth;
  c.height = dstHeight;
  c.paperWhite = params.paperWhiteNits / 80.0f;
  c.headroom = params.headroom < 1.0f ? 1.0f : params.headroom;
  c.strength = params.strength;
  c.colourPreserve = params.colourPreserve;
  c.highlightProtect = params.highlightProtect;
  c.split = params.split;

  ID3D12DescriptorHeap* heaps[] = {heap_.Get()};
  cl->SetDescriptorHeaps(1, heaps);
  cl->SetComputeRootSignature(rootSignature_.Get());
  cl->SetPipelineState(pso);
  cl->SetComputeRootDescriptorTable(0, gpu);
  cl->SetComputeRoot32BitConstants(1, sizeof(Constants) / 4, &c, 0);
  cl->Dispatch((dstWidth + 7) / 8, (dstHeight + 7) / 8, 1);
}

void NrColorBridge::RecordCompose(ID3D12GraphicsCommandList* cl, ID3D12Resource* frame,
                                  ID3D12Resource* shown, ID3D12Resource* model,
                                  ID3D12Resource* dst, uint32_t dstWidth, uint32_t dstHeight,
                                  const NrBridgeParams& params, uint32_t slot) {
  Record(cl, compose_.Get(), slot, frame, model, shown, dst, dstWidth, dstHeight, params);
}

void NrColorBridge::RecordResample(ID3D12GraphicsCommandList* cl, ID3D12Resource* frame,
                                   ID3D12Resource* dst, uint32_t dstWidth, uint32_t dstHeight,
                                   uint32_t slot) {
  // The compose at strength zero writes the sampled original, exactly.
  NrBridgeParams identity;
  identity.strength = 0.0f;
  identity.highlightProtect = 0.0f;
  identity.split = 0.0f;
  Record(cl, compose_.Get(), slot, frame, frame, frame, dst, dstWidth, dstHeight, identity);
}

void NrColorBridge::RecordEncode(ID3D12GraphicsCommandList* cl, ID3D12Resource* frame,
                                 ID3D12Resource* dst, uint32_t dstWidth, uint32_t dstHeight,
                                 const NrBridgeParams& params, uint32_t slot) {
  Record(cl, encode_.Get(), slot, frame, nullptr, nullptr, dst, dstWidth, dstHeight, params);
}

void NrColorBridge::RecordResolve(ID3D12GraphicsCommandList* cl, ID3D12Resource* frame,
                                  ID3D12Resource* model, ID3D12Resource* dst,
                                  uint32_t dstWidth, uint32_t dstHeight,
                                  const NrBridgeParams& params, uint32_t slot) {
  Record(cl, resolve_.Get(), slot, frame, model, nullptr, dst, dstWidth, dstHeight, params);
}

}  // namespace sidecar
