#include "gpu/NrTemporal.h"

#include <algorithm>

#include "gpu/Shaders/NrTemporal.cs.h"   // generated by dxc at build time

using Microsoft::WRL::ComPtr;

namespace sidecar {
namespace {

constexpr uint32_t kSrvCount = 4;   // shown, result, gainPrev, shownPrev
constexpr uint32_t kUavCount = 3;   // gainOut, resultOut, shownCopy

struct Constants {
  uint32_t width;
  uint32_t height;
  float alphaDark;
  float alphaBright;
  float rejectLo;
  float rejectHi;
  uint32_t spatial;
  uint32_t reset;
};

ComPtr<ID3D12Resource> MakeRgba16f(ID3D12Device* device, uint32_t w, uint32_t h) {
  D3D12_HEAP_PROPERTIES heap{};
  heap.Type = D3D12_HEAP_TYPE_DEFAULT;
  D3D12_RESOURCE_DESC rd{};
  rd.Dimension = D3D12_RESOURCE_DIMENSION_TEXTURE2D;
  rd.Width = w;
  rd.Height = h;
  rd.DepthOrArraySize = 1;
  rd.MipLevels = 1;
  rd.Format = DXGI_FORMAT_R16G16B16A16_FLOAT;
  rd.SampleDesc.Count = 1;
  rd.Flags = D3D12_RESOURCE_FLAG_ALLOW_UNORDERED_ACCESS;
  ComPtr<ID3D12Resource> tex;
  if (FAILED(device->CreateCommittedResource(&heap, D3D12_HEAP_FLAG_NONE, &rd,
                                             D3D12_RESOURCE_STATE_UNORDERED_ACCESS, nullptr,
                                             IID_PPV_ARGS(&tex)))) {
    return nullptr;
  }
  return tex;
}

}  // namespace

std::unique_ptr<NrTemporal> NrTemporal::Create(ID3D12Device* device, uint32_t width,
                                               uint32_t height) {
  if (!device || width == 0 || height == 0) return nullptr;
  std::unique_ptr<NrTemporal> t(new NrTemporal());
  t->device_ = device;
  t->width_ = width;
  t->height_ = height;

  D3D12_DESCRIPTOR_RANGE ranges[2]{};
  ranges[0].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_SRV;
  ranges[0].NumDescriptors = kSrvCount;
  ranges[0].BaseShaderRegister = 0;
  ranges[1].RangeType = D3D12_DESCRIPTOR_RANGE_TYPE_UAV;
  ranges[1].NumDescriptors = kUavCount;
  ranges[1].BaseShaderRegister = 0;
  ranges[1].OffsetInDescriptorsFromTableStart = kSrvCount;

  D3D12_ROOT_PARAMETER params[2]{};
  params[0].ParameterType = D3D12_ROOT_PARAMETER_TYPE_DESCRIPTOR_TABLE;
  params[0].DescriptorTable.NumDescriptorRanges = 2;
  params[0].DescriptorTable.pDescriptorRanges = ranges;
  params[1].ParameterType = D3D12_ROOT_PARAMETER_TYPE_32BIT_CONSTANTS;
  params[1].Constants.Num32BitValues = sizeof(Constants) / 4;
  params[1].Constants.ShaderRegister = 0;

  D3D12_ROOT_SIGNATURE_DESC rsd{};
  rsd.NumParameters = 2;
  rsd.pParameters = params;

  ComPtr<ID3DBlob> blob, error;
  if (FAILED(D3D12SerializeRootSignature(&rsd, D3D_ROOT_SIGNATURE_VERSION_1, &blob, &error))) {
    return nullptr;
  }
  if (FAILED(device->CreateRootSignature(0, blob->GetBufferPointer(), blob->GetBufferSize(),
                                         IID_PPV_ARGS(&t->rootSignature_)))) {
    return nullptr;
  }
  D3D12_COMPUTE_PIPELINE_STATE_DESC psd{};
  psd.pRootSignature = t->rootSignature_.Get();
  psd.CS.pShaderBytecode = g_NrTemporalCS;
  psd.CS.BytecodeLength = sizeof(g_NrTemporalCS);
  if (FAILED(device->CreateComputePipelineState(&psd, IID_PPV_ARGS(&t->pipeline_)))) {
    return nullptr;
  }

  D3D12_DESCRIPTOR_HEAP_DESC hd{};
  hd.Type = D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV;
  hd.NumDescriptors = kSrvCount + kUavCount;
  hd.Flags = D3D12_DESCRIPTOR_HEAP_FLAG_SHADER_VISIBLE;
  if (FAILED(device->CreateDescriptorHeap(&hd, IID_PPV_ARGS(&t->heap_)))) return nullptr;
  t->descriptorSize_ =
      device->GetDescriptorHandleIncrementSize(D3D12_DESCRIPTOR_HEAP_TYPE_CBV_SRV_UAV);

  for (int i = 0; i < 2; ++i) {
    t->gain_[i] = MakeRgba16f(device, width, height);
    t->shown_[i] = MakeRgba16f(device, width, height);
    if (!t->gain_[i] || !t->shown_[i]) return nullptr;
  }
  return t;
}

void NrTemporal::Transition(ID3D12GraphicsCommandList* cl, ID3D12Resource* r,
                            D3D12_RESOURCE_STATES a, D3D12_RESOURCE_STATES b) {
  if (!r || a == b) return;
  D3D12_RESOURCE_BARRIER barrier{};
  barrier.Type = D3D12_RESOURCE_BARRIER_TYPE_TRANSITION;
  barrier.Transition.pResource = r;
  barrier.Transition.Subresource = D3D12_RESOURCE_BARRIER_ALL_SUBRESOURCES;
  barrier.Transition.StateBefore = a;
  barrier.Transition.StateAfter = b;
  cl->ResourceBarrier(1, &barrier);
}

void NrTemporal::Record(ID3D12GraphicsCommandList* cl, ID3D12Resource* shown,
                        ID3D12Resource* result, ID3D12Resource* resultOut,
                        const Params& params) {
  if (!cl || !shown || !result || !resultOut) return;
  constexpr auto kUav = D3D12_RESOURCE_STATE_UNORDERED_ACCESS;
  constexpr auto kSrv = D3D12_RESOURCE_STATE_NON_PIXEL_SHADER_RESOURCE;

  const uint32_t prev = current_ ^ 1u;
  Transition(cl, gain_[prev].Get(), kUav, kSrv);
  Transition(cl, shown_[prev].Get(), kUav, kSrv);

  auto cpu = heap_->GetCPUDescriptorHandleForHeapStart();
  D3D12_SHADER_RESOURCE_VIEW_DESC srv{};
  srv.ViewDimension = D3D12_SRV_DIMENSION_TEXTURE2D;
  srv.Shader4ComponentMapping = D3D12_DEFAULT_SHADER_4_COMPONENT_MAPPING;
  srv.Texture2D.MipLevels = 1;
  ID3D12Resource* sources[kSrvCount] = {shown, result, gain_[prev].Get(), shown_[prev].Get()};
  for (ID3D12Resource* source : sources) {
    srv.Format = source->GetDesc().Format;
    device_->CreateShaderResourceView(source, &srv, cpu);
    cpu.ptr += descriptorSize_;
  }
  D3D12_UNORDERED_ACCESS_VIEW_DESC uav{};
  uav.Format = DXGI_FORMAT_R16G16B16A16_FLOAT;
  uav.ViewDimension = D3D12_UAV_DIMENSION_TEXTURE2D;
  ID3D12Resource* targets[kUavCount] = {gain_[current_].Get(), resultOut, shown_[current_].Get()};
  for (ID3D12Resource* target : targets) {
    device_->CreateUnorderedAccessView(target, nullptr, &uav, cpu);
    cpu.ptr += descriptorSize_;
  }

  Constants c{};
  c.width = width_;
  c.height = height_;
  c.alphaDark = std::clamp(params.smoothing, 0.0f, 0.95f);
  c.alphaBright = c.alphaDark * 0.5f;
  c.rejectLo = params.rejectLo;
  c.rejectHi = params.rejectHi;
  c.spatial = params.spatial ? 1u : 0u;
  c.reset = reset_ ? 1u : 0u;

  ID3D12DescriptorHeap* heaps[] = {heap_.Get()};
  cl->SetDescriptorHeaps(1, heaps);
  cl->SetComputeRootSignature(rootSignature_.Get());
  cl->SetPipelineState(pipeline_.Get());
  cl->SetComputeRootDescriptorTable(0, heap_->GetGPUDescriptorHandleForHeapStart());
  cl->SetComputeRoot32BitConstants(1, sizeof(Constants) / 4, &c, 0);
  cl->Dispatch((width_ + 7) / 8, (height_ + 7) / 8, 1);

  Transition(cl, gain_[prev].Get(), kSrv, kUav);
  Transition(cl, shown_[prev].Get(), kSrv, kUav);

  current_ = prev;
  reset_ = false;
}

}  // namespace sidecar
